<?= $this->doctype() ?>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

<?= $this->headTitle()->prepend('i-MSCP internet Multi Server Control Panel')->setAutoEscape(false) ?>
    
<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
    ->appendStylesheet($this->basePath('vendor/bootstrap/dist/css/bootstrap.min.css'))
    ->appendStylesheet($this->basePath('vendor/font-awesome/css/font-awesome.min.css'))
    ->appendStylesheet($this->basePath('vendor/nprogress/nprogress.css'))
    ->appendStylesheet($this->basePath('css/custom.min.css'))
?>

</head>
<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <?= $this->content ?>
    </div>
</div>
<?= $this->inlineScript()
    ->appendFile($this->basePath('vendor/jquery/dist/jquery.min.js'))
    ->appendFile($this->basePath('vendor/bootstrap/dist/js/bootstrap.min.js'))
    ->appendFile($this->basePath('vendor/fastclick/lib/fastclick.js'))
    ->appendFile($this->basePath('vendor/nprogress/nprogress.js'))
    ->appendFile($this->basePath('js/custom.min.js'))
?>

</body>
</html>
